server:
  port: 8080
  servlet:
    context-path: /car-fleet-manager
    encoding:
      force: true
  shutdown: graceful
spring:
  application:
    name: car-fleet-manager
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${car-fleet-manager.datasource.url}
    password: ${car-fleet-manager.datasource.password}
    username: ${car-fleet-manager.datasource.username}
    hikari:
      maximum-pool-size: ${car-fleet-manager.datasource.hikari.maximum-pool-size}
  web:
    resources:
      add-mappings: false
  jpa:
    open-in-view: ${car-fleet-manager.jpa.open-in-view}
    properties:
      hibernate:
        enable_lazy_load_no_trans: ${car-fleet-manager.jpa.properties.hibernate.enable_lazy_load_no_trans}
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    hibernate:
      ddl-auto: ${car-fleet-manager.jpa.hibernate.ddl-auto}
    show-sql: ${car-fleet-manager.jpa.show-sql}
  h2:
    console:
      enabled: ${car-fleet-manager.h2.console.enabled}
      path: ${car-fleet-manager.h2.console.path}
      settings:
        web-allow-others: ${car-fleet-manager.h2.console.settings.web-allow-others}
  flyway:
    enabled: ${car-fleet-manager.flyway.enabled}
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: ${car-fleet-manager.flyway.clean-disabled:true}
    validate-on-migrate: ${car-fleet-manager.flyway.validate-on-migrate:true}
    installed-by: ${spring.application.name}
    placeholder-replacement: true
    fail-on-missing-locations: true
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null

springdoc:
  swagger-ui:
    enabled: ${car-fleet-manager.springdoc.swagger-ui.enabled}
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

openapi-servers-urls: ${car-fleet-manager.openapi-servers-urls}

logging:
  pattern:
    console: "%red(%d{yyyy-MM-dd'T'HH:mm:ssXXX}) %magenta([%thread]) [${spring.application.name}, %X{traceId:-}, %X{spanId:-}] %highlight(%-5level) %logger{36}.%M - %msg%n"
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR